### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by fatlazycat** [tsuraan/bytestring-arbitrary#1]
Hi, appears the pre GHC 7.10 is released as 0.03 ?

Can the version be bumped and release to hackage ?

Thanks

**Comment by tsuraan** [comment]
Shoot, sorry for missing this. I'll try to get this done tonight.

**Comment by tsuraan** [comment]
And, it's uploaded. Sorry for the delay, in answering your ticket and in uploading the package. I really thought I had done that already...

**Comment by fatlazycat** [comment]
Thanks
