### ISSUE TITLE
GHC8.6 compatibility

### ISSUE THREAD

**Issue by Shimuuar** [tsuraan/bytestring-arbitrary#10]
bytestring-arbitrary has constraint `base < 4.12` while it could be built and works fine with GHC8.6. Could you please relax version constraint on hackage?

**Comment by tsuraan** [comment]
Okay, it's now on `base < 4.13` in github as well as on hackage. Hopefully that works (unless I need to bump the base constraint again...).

**Comment by Shimuuar** [comment]
Thanks!  GHC8.8 will be released in few month I think.
