### ISSUE TITLE
Use of LLVM

### ISSUE THREAD

**Issue by fatlazycat** [tsuraan/bytestring-arbitrary#2]
Is it important ? 

As having issue using this lib under travis and it's default install of ubuntu precise and getting llvm 3.5.2 installed.

Currently just cloned the repo and remove the llvm options.

Thanks

**Comment by tsuraan** [comment]
I ran the criterion benchmarks with llvm enabled and disabled, and saw no difference at all. I've uploaded a 0.1.0 release with llvm pulled out of the flags.

My ultimate plan with this is to be able to have a `SizedArbByteString n` type that lets you have a type signature like `sometest :: SizedArbByteString 10000 -> Property`. Once I put that in, I'll make a 1.0.0 release, but I haven't been in a hurry. Now that people seem to actually be using this library, maybe I'll sit down and do that...
