### ISSUE TITLE
Please release master branch as new version on Hackage

### ISSUE THREAD

**Issue by runeksvendsen** [tsuraan/bytestring-arbitrary#5]
Hello

Could you release the current `master` branch as a new version on Hackage? Upping the base dependency bound to `< 4.10` is needed for my app, so I would find it very useful to have this available from Hackage. 

Thank you!

**Comment by tsuraan** [comment]
I finally uploaded a new version! Sorry for the delay, I haven't been a great maintainer lately. It's up now, anyhow.
